public class ResultTask extends Thread {
    public void run(){
        System.out.println("Result Generated by : "+Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
        t1.run(); // Normal Execution -> Always the main Thread
        t1.start(); // Multi Threading     --> T-0, T-1, & so on....
    }
}

/*
➡️Points to remember:-

start() internally calls run()
Thread cannot be started twice.
*/